### PR TITLE
Check formatting on CI

### PR DESCRIPTION
**Pull request by casey**
I also added a clippy run, but it had a bunch of scary complaints, so I gave up.

### CODE REVIEW

**Comment by casey** [comment]
I got clippy to run without complaining by not running it on all targets. Adding --all-targets makes it complain, but that's just tests and or benchmarks.

**Comment by cberner** [comment]
I just merged a fix for all the Clippy errors. Want to rebase? Also, can you pin the rust version on the CI? I'd like to avoid it breaking unexpectedly when new versions are released

**Comment by casey** [comment]
Just rebased and fixed some warnings.

Regarding pinning rust to the latest version, I've found that unless you're enforcing a MSRV, it's on balance better to use stable. New versions of rust have often substantial improvements to compilation speed, and it's nice to get those without having to remember to upgrade. Breakages are infrequent enough that they're not particularly annoying. Your call of course!

**Comment by cberner** [comment]
That makes sense. Ok lets leave it on stable for now, and I'll pin it if it becomes annoying

**Comment by casey** [comment]
Fixed the last of the warnings.

**Comment by cberner** [comment]
Merged. Thanks!

**Pull request merged**
