### PR TITLE
Add `Database::increment_transaction_id`

### PR DESCRIPTION
**Pull request by casey**
I was thinking that this could stand to be deduplicated.

### CODE REVIEW

**Review by cberner — APPROVED** [review]
Can you rebase?

**Comment by casey** [comment]
Done! There should also be an `Update` button that you can use to merge latest master, and then you can squash merge it down to one commit.

**Comment by cberner** [comment]
Oh nice! I missed that button. I've been wishing they would add a feature like that for a while :)

**Comment by casey** [comment]
Also, if you want, you can disable rebase and merge comments, and only allow squash merges, in case you want to keep your commit history clean.

**Comment by cberner** [comment]
Ya, I have merge disabled, but I often use rebase for my own changes or if the PR has nicely structured commits

**Pull request merged**
