### PR TITLE
Add sanakirja to benchmarks

### PR DESCRIPTION
**Pull request by cberner**

### CODE REVIEW

**Comment by Kerollmops** [comment]
What are the benchmarks results, then? 😃

**Comment by cberner** [comment]
```
+--------------------+--------------+------------+--------+---------+--------+-----------+
|                    | redb (1PC+C) | redb (2PC) | lmdb   | rocksdb | sled   | sanakirja |
+========================================================================================+
| bulk load          | 1907ms       | 1495ms     | 1171ms | 5670ms  | 4878ms | 1084ms    |
|--------------------+--------------+------------+--------+---------+--------+-----------|
| individual writes  | 242ms        | 403ms      | 421ms  | 731ms   | 665ms  | 401ms     |
|--------------------+--------------+------------+--------+---------+--------+-----------|
| batch writes       | 2538ms       | 2757ms     | 1919ms | 1592ms  | 1461ms | 2150ms    |
|--------------------+--------------+------------+--------+---------+--------+-----------|
| random reads       | 621ms        | 658ms      | 581ms  | 5701ms  | 1530ms | 631ms     |
|--------------------+--------------+------------+--------+---------+--------+-----------|
| random reads       | 646ms        | 667ms      | 577ms  | 5634ms  | 1393ms | 634ms     |
|--------------------+--------------+------------+--------+---------+--------+-----------|
| random reads       | 645ms        | 649ms      | 580ms  | 5511ms  | 1386ms | 646ms     |
|--------------------+--------------+------------+--------+---------+--------+-----------|
| random range reads | 1572ms       | 1574ms     | 1101ms | 8996ms  | 4662ms | 1049ms    |
|--------------------+--------------+------------+--------+---------+--------+-----------|
| random range reads | 1594ms       | 1578ms     | 1015ms | 9046ms  | 4702ms | 1083ms    |
|--------------------+--------------+------------+--------+---------+--------+-----------|
| random range reads | 1530ms       | 1579ms     | 1046ms | 9041ms  | 4697ms | 1089ms    |
|--------------------+--------------+------------+--------+---------+--------+-----------|
| removals           | 1361ms       | 1185ms     | 716ms  | 2566ms  | 2024ms | 1138ms    |
+--------------------+--------------+------------+--------+---------+--------+-----------+
```

Sanakirja is impressively fast!

**Comment by Kerollmops** [comment]
Hey @cberner,

Do you think you could update the graph on the README with the one in your previous message?

Have a nice day 🌻

**Comment by cberner** [comment]
yep, I'll update them shortly. I have some newer benchmarks that also include multi-threaded read workloads. Surprisingly Sanakirja does poorly on that benchmark.

**Pull request merged**
