### PR TITLE
Add option to set a repair callback

### LINKED ISSUE #639: Provide a way to test if a database file needs repair before opening it
For large redb database files, the repair performed when opening a database that has not been shut down cleanly takes a long time (often more than 30 minutes for the ordinals index when running with `--index-sats`). We can't currently warn the user that a repair is necessary, so we often have users assuming `ord` hangs and then killing the process.

What would be the best way to see if `mem.needs_repair()` is true for a given database file before calling `Database::new`?

### PR DESCRIPTION
**Pull request by cberner**
This allows the user to abort the repair process and receive progress notifications

Fixes #639

### CODE REVIEW

**Comment by cberner** [comment]
@veryordinally / @raphjaph can you take a look at this API when you get a chance? Will merge it, if it looks like it covers your use case

**Comment by casey** [comment]
Nice! This works for us. It looks like `Self::verify_primary_checksums(mem)` is called first, before the repair callback is invoked. Can this take a long time? If so, it would be nice to do a quick check if anything that takes a long time is going to happen, and call `repair_callback` first if so. Related, if `repair_callback` is called first, then having `progress` return `0` for the first call would avoid needing to check if we should skip printing the message, i.e., we could just do `if handle.progress() == 0.0 { print_message() }`.

**Comment by cberner** [comment]
I think that's already implemented. It's just in the caller of `do_repair`. See here: https://github.com/cberner/redb/pull/700/files#diff-7d7d3a6ce5c2a3e8b39ce4f49b78a71365c8e06c0d9ddb78bc2dca68bfeb4a5bR683-R688

**Comment by casey** [comment]
Ah, okay awesome. Looks good to me!

**Comment by cberner** [comment]
I would recommend against `if handle.progress() == 0.0` though. The API doesn't guarantee that the first call will be with a progress value of `0.0` and I might find some reason to change it in the future. Although that does seem unlikely

**Pull request merged**
