### PR TITLE
Enable the `cast_*` clippy option to deny

### LINKED ISSUE #362: Remove usage of `as X` for X < 64, including `as usize`
This should be banned by the regex in the CI too, because it could silently truncate values.

### PR DESCRIPTION
**Pull request by ever0de**
resolved #362
ref: <https://github.com/cberner/xxh3/pull/1>

>It'll be easiest for me to review your changes if you submit a series of PRs that touch only a few files and keep the changes to 100 lines or so. That'll help get them merged quickly so that you don't hit too many merge conflicts with other changes

Sorry for going over 100 lines. Commits are separated according to the content, but if it is necessary to divide the pull request for enabling the clippy option, I will divide it.

### CODE REVIEW

**Comment by ever0de** [comment]
Resolve conflict (from upstream/master)

**Comment by ever0de** [comment]
image
Oh.. there is a clippy I missed on xxh3. I will correct it.

**Comment by ever0de** [comment]
reference: https://github.com/cberner/xxh3/pull/2

**Comment by ever0de** [comment]
<https://github.com/cberner/redb/blob/master/src/tree_store/page_store/xxh3.rs#L250-L253>
Should the result of this u128 * u128 be truncated?

ref: <https://github.com/cberner/redb/actions/runs/3120949904/jobs/5062008684#step:11:104>

**Comment by cberner** [comment]
> https://github.com/cberner/redb/blob/a5e86f3f32d47d259cac239cb639cc03c818a332/src/tree_store/page_store/xxh3.rs#L250-L253
> 
> There seems to be a case where it is right to truncate in some test cases. Should I truncate it in this case? ref: https://github.com/cberner/redb/actions/runs/3120949904/jobs/5062008684#step:11:104

Yes, that one should truncate. I checked the reference implementation and it does the same thing: https://github.com/Cyan4973/xxHash/blob/dev/xxhash.h#L3643-L3647

**Comment by ever0de** [comment]
> > https://github.com/cberner/redb/blob/a5e86f3f32d47d259cac239cb639cc03c818a332/src/tree_store/page_store/xxh3.rs#L250-L253
> > 
> > There seems to be a case where it is right to truncate in some test cases. Should I truncate it in this case? ref: https://github.com/cberner/redb/actions/runs/3120949904/jobs/5062008684#step:11:104
> 
> Yes, that one should truncate. I checked the reference implementation and it does the same thing: https://github.com/Cyan4973/xxHash/blob/dev/xxhash.h#L3643-L3647

Aha Then, I will refer to the code over there and try to edit the xxh3 repository first. Thank you for answer!

**Comment by ever0de** [comment]
Recovered based on testing.

ref: https://github.com/cberner/xxh3/pull/5

**Comment by cberner** [comment]
Merged. Thanks!

**Pull request merged**
