### PR TITLE
Ignore benchmark temporary files

### PR DESCRIPTION
**Pull request by casey**

### CODE REVIEW

**Comment by cberner** [comment]
I think the thing to do here is fix the benchmark so it doesn't leak files. I guess it's not possible in every case, but a ctrl-C signal handler would solve most of them I think. How did you end up with leaked files?

**Comment by casey** [comment]
How about using `tempfile::tempfile()` and `tempfile::tempdir()` to create tempfiles in `$TMPDIR`, which wouldn't show up in git and would get cleaned up eventually when the system clears the tmpdir?

**Comment by cberner** [comment]
It used to do that, but I changed it because on some distros /tmp is a `tmpfs`: https://github.com/cberner/redb/issues/282

Maybe it could detect that it was a tmpfs and require the user to configure a different directory via an environment variable

**Comment by casey** [comment]
In that case, how about using `./tmp`, adding it to gitignore, and not bothering to clean it up? That seems easier than having to add a ctrl-c handler to all tests that create temporary files.

**Comment by cberner** [comment]
I moved it into .benchmark and also added the ctrl-c handler. Turned out to be pretty easy :)

**Pull request closed without merging**
