### PR TITLE
Some very small adj.

### PR DESCRIPTION
**Pull request by yukibtc**
* Derive `Clone` for `Database`
* Change `compact` method to take `&self` instead of `&mut self`

### CODE REVIEW

**Comment by cberner** [comment]
This is not safe. `compact()` needs to take `&mut self` to ensure there are no outstanding transactions since it needs to relocate all the pages

**Comment by yukibtc** [comment]
Is the commit related to the derive `Clone` acceptable? If looks good, I'll reopen a PR with only that commit.

---

> This is not safe. compact() needs to take &mut self to ensure there are no outstanding transactions since it needs to relocate all the pages

Ah, sorry, I saw now the comment in the code. 
Is there a way we can remove the `&mut self` from the `compact`? At the moment this force me to wrap the `Database` inside an `Arc<RwLock<T>>`, only to support compaction.

**Comment by cberner** [comment]
> Is the commit related to the derive Clone acceptable? If looks good, I'll reopen a PR with only that commit.

No, that has the same problem as removing `&mut` from `compact()`. Then it would be possible to have two `Database`s and call `compact()` while the other had outstanding transactions

**Comment by cberner** [comment]
> Is there a way we can remove the &mut self from the compact?

I don't think so. This is an inherent design limitation of the MVCC model in redb

**Pull request closed without merging**
