### PR TITLE
clear up bounds in `src`

### PR DESCRIPTION
**Pull request by notJoon**
## Description
clear up bounds in `src`.

I thought it would be better to organize it to increase readability. So I organized it. If possible, I'll clean up the other codes like `src/tree_store` and `page_store`

I'm not sure if it's ok. Please tell me if I did anything wrong. I am ready to edit at any time. And also, thanks for your time.

## TODO

- [x] clear tree_store
- [x] clear page_store

### CODE REVIEW

**Review by cberner — CHANGES_REQUESTED** [review]
I prefer the inline trait bounds. Too many years of Java programming, and so it looks more natural to me than the `where` form :)

I'm happy to take the documentation improvements though, if you want to just submit those

**Comment by notJoon** [comment]
Thanks. I'll try to participate from time to time.

**Comment by cberner** [comment]
Sorry if my last comment wasn't clear, but I meant that I like the current form of type parameters. i.e. `pub struct TableDefinition<'a, K: RedbKey + ?Sized, V: RedbValue + ?Sized>` and not the `where` form that you changed it to.

**Comment by notJoon** [comment]
Oh, I didn't understand it well. Anyway, thank you for your feedback.

**Pull request closed without merging**
